# Generated by Django 2.2.6 on 2019-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True, max_length=2048)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('genres', models.CharField(blank=True, max_length=120)),
                ('abs_poster', models.CharField(blank=True, max_length=500)),
                ('abs_screen', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
