# Generated by Django 2.2.6 on 2019-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='abs_poster',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='film',
            name='abs_screen',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
