# Generated by Django 2.2.6 on 2019-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinogo', '0002_auto_20191001_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='abs_poster',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
