# Generated by Django 2.2.6 on 2019-10-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinogo', '0003_auto_20191001_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
    ]
