# Generated by Django 2.2.6 on 2019-10-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinogo', '0004_auto_20191011_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='abs_poster',
        ),
        migrations.RemoveField(
            model_name='film',
            name='abs_screen',
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_screen', models.TextField(blank=True, max_length=1024)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='kinogo.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_poster', models.CharField(blank=True, max_length=128)),
                ('films', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='kinogo.Film')),
            ],
        ),
    ]
